# 网站的基本设置
title: My Jekyll Site
description: This is my awesome site built with Jekyll!
url: "https://snivallus.github.io/Multi-agent/"  # 你的 GitHub Pages URL

# 默认的语言设置
lang: en

# 主题设置（例如使用 Jekyll 官方的 Primer 主题）
theme: jekyll-theme-primer

# 其他可选的设置
baseurl: "Multi-agent/" 

# Jekyll 插件配置（如果你需要）
plugins:
  - jekyll-seo-tag  # 用于 SEO 设置
  - jekyll-paginate  # 分页功能
  - jekyll-github-metadata  # GitHub 页面元数据

# 如果你有自定义的主题样式文件，配置如下
sass:
  style: compressed
  load_paths:
    - _sass

# 排除文件（如果有不需要在最终站点生成的文件，可以在这里排除）
exclude:
  - README.md  # 排除 README 文件

# 生成 HTML 时的行为设置
markdown: kramdown
highlighter: pygments
